# Generated by Django 4.2.16 on 2026-03-31 18:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SOSAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('called_member', 'Called Member'), ('called_contact', 'Called Emergency Contact'), ('sent_location', 'Sent Location'), ('marked_safe', 'Marked Safe'), ('escalated', 'Escalated')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SOS Action',
                'db_table': 'safety_sosaction',
            },
        ),
        migrations.CreateModel(
            name='SOSAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual'), ('stationary', 'Stationary'), ('deviation', 'Route Deviation')], max_length=15)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('accuracy_meters', models.FloatField(blank=True, null=True)),
                ('deviation_distance_m', models.FloatField(blank=True, null=True)),
                ('stationary_minutes', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm')], default='active', max_length=15)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('emergency_contact_notified', models.BooleanField(default=False)),
                ('chief_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SOS Alert',
                'db_table': 'safety_sosalert',
            },
        ),
    ]
