# Generated by Django 4.2.16 on 2026-03-31 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('safety', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='sosaction',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='safety.sosalert'),
        ),
        migrations.AddField(
            model_name='sosaction',
            name='taken_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sosalert',
            index=models.Index(fields=['trip', 'status'], name='safety_sosa_trip_id_b60549_idx'),
        ),
    ]
