# Generated by Django 4.2.16 on 2026-03-31 18:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('sos_alert', 'SOS Alert'), ('join_request', 'Join Request'), ('approved', 'Join Approved'), ('chat_message', 'Chat Message'), ('karma_level', 'Karma Level Up'), ('trip_reminder', 'Trip Reminder'), ('proximity_warning', 'Proximity Warning')], max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'db_table': 'notifications_notification',
            },
        ),
    ]
