# Generated by Django 4.2.16 on 2026-04-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('sos_alert', 'SOS Alert'), ('join_request', 'Join Request'), ('join_approved', 'Join Approved'), ('join_declined', 'Join Declined'), ('approved', 'Approved'), ('chat_message', 'Chat Message'), ('karma_level', 'Karma Level Up'), ('trip_reminder', 'Trip Reminder'), ('proximity_warning', 'Proximity Warning'), ('trip_ended', 'Trip Ended'), ('review_reminder', 'Review Reminder')], max_length=25),
        ),
    ]
