# Generated by Django 4.2.16 on 2026-06-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('sos_alert', 'SOS Alert'), ('join_request', 'Join Request'), ('join_approved', 'Join Approved'), ('join_declined', 'Join Declined'), ('approved', 'Approved'), ('chat_message', 'Chat Message'), ('karma_level', 'Karma Level Up'), ('trip_reminder', 'Trip Reminder'), ('proximity_warning', 'Proximity Warning'), ('trip_ended', 'Trip Ended'), ('review_reminder', 'Review Reminder'), ('payment_due', 'Payment Due'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('refund_processed', 'Refund Processed'), ('payout_released', 'Payout Released'), ('trip_cancelled', 'Trip Cancelled')], max_length=25),
        ),
    ]
