# Generated by Django 4.2.16 on 2026-04-06 00:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_emailverification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='group_size_pref',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='pace',
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='trip_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
