# Generated by Django 4.2.16 on 2026-04-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_budget_pace_groupsize_from_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
