# Generated by Django 4.2.16 on 2026-04-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_cover_url_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
