# Generated by Django 4.2.16 on 2026-04-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_username_name_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_position',
            field=models.CharField(default='50% 50%', max_length=20),
        ),
    ]
