# Generated by Django 4.2.16 on 2026-06-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_cover_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clawback_owed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
