# Generated by Django 4.2.16 on 2026-09-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_clawback_owed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payout_probation_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
