# Generated by Django 4.2.16 on 2026-09-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_payout_probation_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='retired_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
    ]
