# Generated by Django 4.2.16 on 2026-03-31 18:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=300)),
                ('poll_type', models.CharField(choices=[('yes_no', 'Yes / No'), ('multiple_choice', 'Multiple Choice'), ('rating', 'Rating')], max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('location_context', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('time_impact_minutes', models.IntegerField(blank=True, null=True)),
                ('budget_impact_ghs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Poll',
                'db_table': 'polls_poll',
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Poll Option',
                'db_table': 'polls_polloption',
                'ordering': ['poll', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes_no_value', models.BooleanField(blank=True, null=True)),
                ('rating_value', models.IntegerField(blank=True, null=True)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.polloption')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.poll')),
            ],
            options={
                'verbose_name': 'Poll Vote',
                'db_table': 'polls_pollvote',
            },
        ),
    ]
