# Generated by Django 4.2.16 on 2026-03-31 18:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_at_checkin', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('accuracy_meters', models.FloatField(blank=True, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Check-in',
                'db_table': 'trips_checkin',
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_type', models.CharField(choices=[('safety', 'Safety'), ('harassment', 'Harassment'), ('fraud', 'Fraud'), ('rule_violation', 'Rule Violation'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('evidence_urls', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Incident Report',
                'db_table': 'trips_incidentreport',
            },
        ),
        migrations.CreateModel(
            name='ItineraryStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('geofence_radius', models.IntegerField(default=100)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Itinerary Stop',
                'db_table': 'trips_itinerarystop',
                'ordering': ['trip', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SavedTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Saved Trip',
                'db_table': 'trips_savedtrip',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('destination_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('meeting_point', models.CharField(blank=True, max_length=200, null=True)),
                ('meeting_point_coords', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('cover_url', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('drive_time', models.CharField(blank=True, choices=[('under_1h', 'Under 1hr'), ('1_2h', '1–2hrs'), ('2_4h', '2–4hrs'), ('4_6h', '4–6hrs'), ('6h_plus', '6hrs+')], max_length=10, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('spots_total', models.IntegerField(default=10)),
                ('entry_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_note', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('unlisted', 'Unlisted')], default='public', max_length=20)),
                ('group_karma', models.IntegerField(default=0)),
                ('departure_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trip',
                'db_table': 'trips_trip',
            },
        ),
        migrations.CreateModel(
            name='TripMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('chief', 'Chief'), ('scout', 'Scout'), ('member', 'Member')], default='member', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('removed', 'Removed')], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.CharField(blank=True, max_length=300, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('karma_earned', models.IntegerField(default=0)),
                ('is_banned', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Trip Member',
                'db_table': 'trips_tripmember',
            },
        ),
        migrations.CreateModel(
            name='TripPriceCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Trip Price Cover',
                'db_table': 'trips_trippricecover',
            },
        ),
        migrations.CreateModel(
            name='TripRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall', models.IntegerField()),
                ('organisation', models.IntegerField(blank=True, null=True)),
                ('safety', models.IntegerField(blank=True, null=True)),
                ('fun', models.IntegerField(blank=True, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('review', models.TextField(blank=True, max_length=500, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trip Rating',
                'db_table': 'trips_triprating',
            },
        ),
        migrations.CreateModel(
            name='TripTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Trip Tag',
                'db_table': 'trips_triptag',
            },
        ),
    ]
