# Generated by Django 4.2.16 on 2026-03-31 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='triprating',
            name='rated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triprating',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triprating',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='trippricecover',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_covers', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='tripmember',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tripmember',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='tripmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='chief',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedtrip',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='savedtrip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itinerarystop',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkin',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='trips.itinerarystop'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='trips.trip'),
        ),
        migrations.AlterUniqueTogether(
            name='triptag',
            unique_together={('trip', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='triprating',
            unique_together={('trip', 'rater', 'rated_user')},
        ),
        migrations.AlterUniqueTogether(
            name='trippricecover',
            unique_together={('trip', 'item')},
        ),
        migrations.AddIndex(
            model_name='tripmember',
            index=models.Index(fields=['trip', 'status'], name='trips_tripm_trip_id_12f5f0_idx'),
        ),
        migrations.AddIndex(
            model_name='tripmember',
            index=models.Index(fields=['trip', 'role'], name='trips_tripm_trip_id_0a4238_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tripmember',
            unique_together={('trip', 'user')},
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status', 'date_start'], name='trips_trip_status_06ee00_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['chief'], name='trips_trip_chief_i_f0b7c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedtrip',
            unique_together={('user', 'trip')},
        ),
        migrations.AddIndex(
            model_name='itinerarystop',
            index=models.Index(fields=['trip', 'order'], name='trips_itine_trip_id_38716d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='checkin',
            unique_together={('trip', 'member', 'stop')},
        ),
    ]
