# Generated by Django 4.2.16 on 2026-04-01 13:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.TextField()),
                ('image_key', models.CharField(max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Trip Image',
                'db_table': 'trips_tripimage',
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='tripimage',
            constraint=models.CheckConstraint(check=models.Q(('order__lte', 4)), name='trip_image_order_max_4'),
        ),
        migrations.AlterUniqueTogether(
            name='tripimage',
            unique_together={('trip', 'order')},
        ),
    ]
