# Generated by Django 4.2.16 on 2026-06-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_add_trip_highlights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripmember',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_payment', 'Awaiting Payment'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('removed', 'Removed')], default='pending', max_length=20),
        ),
    ]
