# Generated by Django 4.2.16 on 2026-06-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_alter_tripmember_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
