# Generated by Django 4.2.16 on 2026-06-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_alter_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarystop',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
