# Generated by Django 4.2.16 on 2026-06-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_backfill_meeting_point_stops'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripmember',
            name='completion_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
