# Generated by Django 4.2.16 on 2026-06-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_tripmember_completion_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='response_evidence_urls',
            field=models.JSONField(default=list),
        ),
    ]
