# Generated by Django 4.2.16 on 2026-06-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_incidentreport_responded_at_incidentreport_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='flag_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='flagged_for_review',
            field=models.BooleanField(default=False),
        ),
    ]
