# Generated by Django 4.2.16 on 2026-06-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_trip_flag_reason_trip_flagged_for_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
