# Generated by Django 4.2.16 on 2026-09-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_trip_end_time_trip_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='distance_meters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
