# Generated by Django 4.2.16 on 2026-09-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_checkin_distance_meters_checkin_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='departure_checkin_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
