# Generated by Django 4.2.16 on 2026-09-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0016_trip_departure_checkin_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='drive_time',
            field=models.CharField(blank=True, choices=[('under_1h', 'Under 1h'), ('1_2h', '1-2h'), ('2_4h', '2-4h'), ('4_6h', '4-6h'), ('6h_plus', '6h+')], max_length=10, null=True),
        ),
    ]
