# Generated by Django 4.2.16 on 2026-03-31 18:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_url', models.TextField()),
                ('video_key', models.CharField(max_length=500)),
                ('thumbnail_url', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.FloatField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('accuracy_meters', models.FloatField(blank=True, null=True)),
                ('watermark_coords', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('watermark_timestamp', models.DateTimeField(blank=True, null=True)),
                ('geofence_validated', models.BooleanField(default=False)),
                ('is_in_recap', models.BooleanField(default=False)),
                ('engagement_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Streak',
                'db_table': 'streaks_streak',
            },
        ),
        migrations.CreateModel(
            name='StreakReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', 'Like'), ('fire', 'Fire'), ('heart', 'Heart'), ('wow', 'Wow')], max_length=10)),
                ('reacted_at', models.DateTimeField(auto_now_add=True)),
                ('streak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='streaks.streak')),
            ],
            options={
                'verbose_name': 'Streak Reaction',
                'db_table': 'streaks_streakreaction',
            },
        ),
    ]
