# Generated by Django 4.2.16 on 2026-03-31 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streaks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streakreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='streak',
            name='stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='streaks', to='trips.itinerarystop'),
        ),
        migrations.AddField(
            model_name='streak',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='streak',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='streakreaction',
            unique_together={('streak', 'user')},
        ),
        migrations.AddIndex(
            model_name='streak',
            index=models.Index(fields=['trip', '-created_at'], name='streaks_str_trip_id_c28fda_idx'),
        ),
        migrations.AddIndex(
            model_name='streak',
            index=models.Index(fields=['stop', '-created_at'], name='streaks_str_stop_id_708837_idx'),
        ),
    ]
