# Generated by Django 4.2.16 on 2026-03-31 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=10)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], max_length=15)),
                ('unlock_criteria', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Badge',
                'db_table': 'karma_badge',
            },
        ),
        migrations.CreateModel(
            name='KarmaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(choices=[('trip_completed', 'Trip Completed'), ('checkin_ontime', 'Check-in On Time'), ('group_rating', 'Group Rating'), ('streak_engagement', 'Streak Engagement'), ('penalty', 'Penalty')], max_length=25)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Karma Log',
                'db_table': 'karma_karmalog',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holders', to='karma.badge')),
            ],
            options={
                'verbose_name': 'User Badge',
                'db_table': 'karma_userbadge',
            },
        ),
    ]
