# Generated by Django 4.2.16 on 2026-09-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='report_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='type',
            field=models.CharField(choices=[('dm', 'Direct Message'), ('group', 'Group'), ('support', 'Travel Together Support')], max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('voice', 'Voice'), ('location', 'Location'), ('streak', 'Streak'), ('poll_result', 'Poll Result'), ('system', 'System'), ('report_ref', 'Report Reference')], default='text', max_length=15),
        ),
    ]
