# Generated by Django 4.2.16 on 2026-09-17 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_is_official_message_report_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportThread',
            fields=[
            ],
            options={
                'verbose_name': 'Support thread',
                'verbose_name_plural': 'Support threads',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chat.conversation',),
        ),
    ]
