# Generated by Django 4.2.16 on 2026-06-12 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0008_alter_trip_status'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank', 'Bank')], default='mobile_money', max_length=15)),
                ('account_number', models.CharField(max_length=30)),
                ('bank_code', models.CharField(max_length=20)),
                ('account_name', models.CharField(blank=True, max_length=120)),
                ('recipient_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_method', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payout Method',
                'db_table': 'payments_payoutmethod',
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kind', models.CharField(choices=[('partial', 'Partial (at departure)'), ('final', 'Final (after trip)')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('paystack_ref', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Payout',
                'db_table': 'payments_payout',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trip', 'kind'], name='payments_pa_trip_id_eeed93_idx')],
            },
        ),
    ]
